### ISSUE TITLE
Referenciar os exemplos à palestra "Precisamos falar de Gradle" 

### ISSUE THREAD

**Issue by CesarNog** [wrpinheiro/gradle-soujava-meetup#1]
Seria uma boa ideia colocar o link para sua palestra "Precisamos falar de Gradle" que está hospedada em: https://pt.slideshare.net/wrpinheiro/precisamos-falar-sobre-gradle no README.md ou na descrição do branch.

**Comment by wrpinheiro** [comment]
Legal @CesarNog, vou alterar!

**Comment by CesarNog** [comment]
Legal, ficou ótimo!
